=== Calinou/godot/doc/class.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="class">
		<xs:complexType>
			<xs:sequence>
				<xs:element type="xs:string" name="brief_description" />
				<xs:element type="xs:string" name="description" />
				<xs:element name="tutorials">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="link" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="title" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constructors" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constructor" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="methods" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="method" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="returns_error" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="number" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="since" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="members" minOccurs="0">
					<xs:complexType>
						<xs:choice maxOccurs="unbounded" minOccurs="0">
							<xs:element name="member">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="setter" />
											<xs:attribute type="xs:string" name="getter" />
											<xs:attribute type="xs:string" name="overrides" use="optional" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:choice>
					</xs:complexType>
				</xs:element>
				<xs:element name="signals" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="signal" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="keywords" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<!-- deprecated -->
									<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
									<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
									<!-- /deprecated -->
									<xs:attribute type="xs:string" name="deprecated" use="optional" />
									<xs:attribute type="xs:string" name="experimental" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="constants" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="constant" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="value" />
											<xs:attribute type="xs:string" name="enum" use="optional" />
											<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											<!-- deprecated -->
											<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
											<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
											<!-- /deprecated -->
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="annotations" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="annotation" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
									<xs:attribute type="xs:string" name="keywords" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="theme_items" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="theme_item" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:simpleContent>
										<xs:extension base="xs:string">
											<xs:attribute type="xs:string" name="name" />
											<xs:attribute type="xs:string" name="data_type" />
											<xs:attribute type="xs:string" name="type" />
											<xs:attribute type="xs:string" name="default" use="optional" />
											<xs:attribute type="xs:string" name="deprecated" use="optional" />
											<xs:attribute type="xs:string" name="experimental" use="optional" />
											<xs:attribute type="xs:string" name="keywords" use="optional" />
										</xs:extension>
									</xs:simpleContent>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operators" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="operator" maxOccurs="unbounded" minOccurs="0">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="return" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element name="param" maxOccurs="unbounded" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:sequence />
												</xs:sequence>
												<xs:attribute type="xs:byte" name="index" />
												<xs:attribute type="xs:string" name="name" />
												<xs:attribute type="xs:string" name="type" />
												<xs:attribute type="xs:string" name="enum" use="optional" />
												<xs:attribute type="xs:boolean" name="is_bitfield" use="optional" />
												<xs:attribute type="xs:string" name="default" use="optional" />
											</xs:complexType>
										</xs:element>
										<xs:element type="xs:string" name="description" />
									</xs:sequence>
									<xs:attribute type="xs:string" name="name" use="optional" />
									<xs:attribute type="xs:string" name="qualifiers" use="optional" />
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute type="xs:string" name="name" />
			<xs:attribute type="xs:string" name="inherits" />
			<!-- deprecated -->
			<xs:attribute type="xs:float" name="version" use="optional" />
			<xs:attribute type="xs:boolean" name="is_deprecated" use="optional" />
			<xs:attribute type="xs:boolean" name="is_experimental" use="optional" />
			<!-- /deprecated -->
			<xs:attribute type="xs:string" name="deprecated" use="optional" />
			<xs:attribute type="xs:string" name="experimental" use="optional" />
			<xs:attribute type="xs:string" name="keywords" use="optional" />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== Calinou/godot/doc/classes/InputEventScreenDrag.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="InputEventScreenDrag" inherits="InputEventFromWindow" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Represents a screen drag event.
	</brief_description>
	<description>
		Stores information about screen drag events. See [method Node._input].
	</description>
	<tutorials>
		<link title="Using InputEvent">$DOCS_URL/tutorials/inputs/inputevent.html</link>
	</tutorials>
	<members>
		<member name="index" type="int" setter="set_index" getter="get_index" default="0">
			The drag event index in the case of a multi-drag event.
		</member>
		<member name="pen_inverted" type="bool" setter="set_pen_inverted" getter="get_pen_inverted" default="false">
			Returns [code]true[/code] when using the eraser end of a stylus pen.
		</member>
		<member name="position" type="Vector2" setter="set_position" getter="get_position" default="Vector2(0, 0)">
			The drag position.
		</member>
		<member name="pressure" type="float" setter="set_pressure" getter="get_pressure" default="0.0">
			Represents the pressure the user puts on the pen. Ranges from [code]0.0[/code] to [code]1.0[/code].
		</member>
		<member name="relative" type="Vector2" setter="set_relative" getter="get_relative" default="Vector2(0, 0)">
			The drag position relative to the previous position (position at the last frame).
			[b]Note:[/b] [member relative] is automatically scaled according to the content scale factor, which is defined by the project's stretch mode settings. This means touch sensitivity will appear different depending on resolution when using [member relative] in a script that handles touch aiming. To avoid this, use [member relative_unscaled] instead.
		</member>
		<member name="relative_unscaled" type="Vector2" setter="set_relative_unscaled" getter="get_relative_unscaled" default="Vector2(0, 0)">
			The drag position relative to the previous position (position at the last frame)., but not scaled according to the content scale factor or calls to [method InputEvent.xformed_by]. This should be preferred over [member relative] for touch aiming regardless of the project's stretch mode.
		</member>
		<member name="tilt" type="Vector2" setter="set_tilt" getter="get_tilt" default="Vector2(0, 0)">
			Represents the angles of tilt of the pen. Positive X-coordinate value indicates a tilt to the right. Positive Y-coordinate value indicates a tilt toward the user. Ranges from [code]-1.0[/code] to [code]1.0[/code] for both axes.
		</member>
		<member name="velocity" type="Vector2" setter="set_velocity" getter="get_velocity" default="Vector2(0, 0)">
			The drag velocity in pixels per second.
			[b]Note:[/b] [member velocity] is automatically scaled according to the content scale factor, which is defined by the project's stretch mode settings. This means touch sensitivity will appear different depending on resolution when using [member velocity] in a script that handles touch aiming. To avoid this, use [member velocity_unscaled] instead.
		</member>
		<member name="velocity_unscaled" type="Vector2" setter="set_velocity_unscaled" getter="get_velocity_unscaled" default="Vector2(0, 0)">
			The drag velocity in pixels per second, but not scaled according to the content scale factor or calls to [method InputEvent.xformed_by]. This should be preferred over [member velocity] for touch aiming regardless of the project's stretch mode.
		</member>
	</members>
</class>

=== Calinou/godot/modules/csg/doc_classes/CSGCylinder3D.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="CSGCylinder3D" inherits="CSGPrimitive3D" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../doc/class.xsd">
	<brief_description>
		A CSG Cylinder shape.
	</brief_description>
	<description>
		This node allows you to create a cylinder (or cone) for use with the CSG system.
		[b]Note:[/b] CSG nodes are intended to be used for level prototyping. Creating CSG nodes has a significant CPU cost compared to creating a [MeshInstance3D] with a [PrimitiveMesh]. Moving a CSG node within another CSG node also has a significant CPU cost, so it should be avoided during gameplay.
	</description>
	<tutorials>
		<link title="Prototyping levels with CSG">$DOCS_URL/tutorials/3d/csg_tools.html</link>
	</tutorials>
	<methods>
		<method name="get_radius" qualifiers="const">
			<return type="float" />
			<description>
			</description>
		</method>
		<method name="set_radius">
			<return type="void" />
			<param index="0" name="radius" type="float" />
			<description>
			</description>
		</method>
	</methods>
	<members>
		<member name="bottom_radius" type="float" setter="set_bottom_radius" getter="get_bottom_radius" default="0.5">
			The radius of the bottom face of the cylinder. If set to [code]0.0[/code], the cylinder will be a cone.
		</member>
		<member name="cone" type="bool" setter="set_cone" getter="is_cone" deprecated="Set [member top_radius] to [code]0.0[/code] instead.">
			If [code]true[/code], the cylinder will be a cone, with the top radius set to [code]0.0[/code].
		</member>
		<member name="height" type="float" setter="set_height" getter="get_height" default="2.0">
			The height of the cylinder.
		</member>
		<member name="material" type="Material" setter="set_material" getter="get_material">
			The material used to render the cylinder.
		</member>
		<member name="radius" type="float" setter="set_top_radius" getter="get_top_radius" deprecated="Use [member top_radius] and [member bottom_radius] instead.">
			The radius of the cylinder.
		</member>
		<member name="sides" type="int" setter="set_sides" getter="get_sides" default="8">
			The number of sides of the cylinder. The higher this number, the more detail there will be in the cylinder.
		</member>
		<member name="smooth_faces" type="bool" setter="set_smooth_faces" getter="get_smooth_faces" default="true">
			If [code]true[/code] the normals of the cylinder are set to give a smooth effect, making the cylinder seem rounded. If [code]false[/code], the cylinder will have a flat shaded look.
		</member>
		<member name="top_radius" type="float" setter="set_top_radius" getter="get_top_radius" default="0.5">
			The radius of the top face of the cylinder. If set to [code]0.0[/code], the cylinder will be a cone.
		</member>
	</members>
</class>

=== Calinou/godot/doc/classes/MeshLibrary.xml
<?xml version="1.0" encoding="UTF-8" ?>
<class name="MeshLibrary" inherits="Resource" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../class.xsd">
	<brief_description>
		Library of meshes.
	</brief_description>
	<description>
		A library of meshes. Contains a list of [Mesh] resources, each with a name and ID. Each item can also include collision and navigation shapes. This resource is used in [GridMap].
	</description>
	<tutorials>
		<link title="3D Kinematic Character Demo">https://godotengine.org/asset-library/asset/2739</link>
		<link title="3D Platformer Demo">https://godotengine.org/asset-library/asset/2748</link>
	</tutorials>
	<methods>
		<method name="clear">
			<return type="void" />
			<description>
				Clears the library.
			</description>
		</method>
		<method name="create_item">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<description>
				Creates a new item in the library with the given ID.
				You can get an unused ID from [method get_last_unused_item_id].
			</description>
		</method>
		<method name="find_item_by_name" qualifiers="const">
			<return type="int" />
			<param index="0" name="name" type="String" />
			<description>
				Returns the first item with the given name, or [code]-1[/code] if no item is found.
			</description>
		</method>
		<method name="get_item_list" qualifiers="const">
			<return type="PackedInt32Array" />
			<description>
				Returns the list of item IDs in use.
			</description>
		</method>
		<method name="get_item_mesh" qualifiers="const">
			<return type="Mesh" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the item's mesh.
			</description>
		</method>
		<method name="get_item_mesh_cast_shadow" qualifiers="const">
			<return type="int" enum="RenderingServer.ShadowCastingSetting" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the item's shadow casting mode.
			</description>
		</method>
		<method name="get_item_mesh_transform" qualifiers="const">
			<return type="Transform3D" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the transform applied to the item's mesh.
			</description>
		</method>
		<method name="get_item_name" qualifiers="const">
			<return type="String" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the item's name.
			</description>
		</method>
		<method name="get_item_navigation_layers" qualifiers="const">
			<return type="int" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the item's navigation layers bitmask.
			</description>
		</method>
		<method name="get_item_navigation_mesh" qualifiers="const">
			<return type="NavigationMesh" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the item's navigation mesh.
			</description>
		</method>
		<method name="get_item_navigation_mesh_transform" qualifiers="const">
			<return type="Transform3D" />
			<param index="0" name="id" type="int" />
			<description>
				Returns the transform applied to the item's navigation mesh.
			</description>
		</method>
		<method name="get_item_preview" qualifiers="const">
			<return type="Texture2D" />
			<param index="0" name="id" type="int" />
			<description>
				When running in the editor, returns a generated item preview (a 3D rendering in isometric perspective). When used in a running project, returns the manually-defined item preview which can be set using [method set_item_preview]. Returns an empty [Texture2D] if no preview was manually set in a running project.
			</description>
		</method>
		<method name="get_item_render_layers" qualifiers="const">
			<return type="int" />
			<param index="0" name="id" type="int" />
			<description>
				Returns item render layers bitmask.
			</description>
		</method>
		<method name="get_item_shapes" qualifiers="const">
			<return type="Array" />
			<param index="0" name="id" type="int" />
			<description>
				Returns an item's collision shapes.
				The array consists of each [Shape3D] followed by its [Transform3D].
			</description>
		</method>
		<method name="get_last_unused_item_id" qualifiers="const">
			<return type="int" />
			<description>
				Gets an unused ID for a new item.
			</description>
		</method>
		<method name="remove_item">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<description>
				Removes the item.
			</description>
		</method>
		<method name="set_item_mesh">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="mesh" type="Mesh" />
			<description>
				Sets the item's mesh.
			</description>
		</method>
		<method name="set_item_mesh_cast_shadow">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="shadow_casting_setting" type="int" enum="RenderingServer.ShadowCastingSetting" />
			<description>
				Sets the item's shadow casting mode to [param shadow_casting_setting].
			</description>
		</method>
		<method name="set_item_mesh_transform">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="mesh_transform" type="Transform3D" />
			<description>
				Sets the transform to apply to the item's mesh.
			</description>
		</method>
		<method name="set_item_name">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="name" type="String" />
			<description>
				Sets the item's name.
				This name is shown in the editor. It can also be used to look up the item later using [method find_item_by_name].
			</description>
		</method>
		<method name="set_item_navigation_layers">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="navigation_layers" type="int" />
			<description>
				Sets the item's navigation layers bitmask.
			</description>
		</method>
		<method name="set_item_navigation_mesh">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="navigation_mesh" type="NavigationMesh" />
			<description>
				Sets the item's navigation mesh.
			</description>
		</method>
		<method name="set_item_navigation_mesh_transform">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="navigation_mesh" type="Transform3D" />
			<description>
				Sets the transform to apply to the item's navigation mesh.
			</description>
		</method>
		<method name="set_item_preview">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="texture" type="Texture2D" />
			<description>
				Sets a texture to use as the item's preview icon in the editor.
			</description>
		</method>
		<method name="set_item_render_layers">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="render_layers" type="int" />
			<description>
				Sets item render layers bitmask.
			</description>
		</method>
		<method name="set_item_shapes">
			<return type="void" />
			<param index="0" name="id" type="int" />
			<param index="1" name="shapes" type="Array" />
			<description>
				Sets an item's collision shapes.
				The array should consist of [Shape3D] objects, each followed by a [Transform3D] that will be applied to it. For shapes that should not have a transform, use [constant Transform3D.IDENTITY].
			</description>
		</method>
	</methods>
</class>
